SS-6180: refactored gumball implementation
shapediver/AppBuilderShared pull request #11
Opened 2024-08-23 09:16 UTC by MajorMeerkatThe3rd

@snabela while the parameter component is not done yet as some more spec is needed, the hooks can already be reviewed!

The changes in the selection parts are actually pretty minor, I now not only return the selected node names, but additionally the selected nodes themselves. As I already had them in the selection events either way, it made sense to not traverse the scene tree another time.

2024-08-25 07:21 UTC, snabela commented on hooks/shapediver/viewer/interaction/gumball/useGumballEvents.ts
> +	}, [selectedNodes, transformedNodes]);
@MajorMeerkatThe3rd let's implement this hook such that the event listener is not re-recreated every time the state of selected or transformed nodes changes.

2024-08-25 07:23 UTC, snabela commented
> @snabela while the parameter component is not done yet as some more spec is needed, the hooks can already be reviewed!
> 
> The changes in the selection parts are actually pretty minor, I now not only return the selected node names, but additionally the selected nodes themselves. As I already had them in the selection events either way, it made sense to not traverse the scene tree another time.

Looks good! I am sorry that some refactoring will be necessary, due to what I did in https://github.com/shapediver/AppBuilderShared/pull/10
🙃

2024-08-28 12:27 UTC, MajorMeerkatThe3rd commented
@snabela please review the new changes, thank you!

2024-08-30 05:50 UTC, snabela commented on hooks/shapediver/viewer/interaction/gumball/useGumball.ts
> +			// whenever this output node changes, we want to create the interaction engine
@MajorMeerkatThe3rd the comment is not clear to me, is it a leftover?

2024-08-30 05:54 UTC, snabela commented on hooks/shapediver/viewer/interaction/gumball/useGumball.ts
> +	const restoreTransformedNodeNames = useCallback((newTransformedNodeNames: { name: string, transformation: number[] }[], oldTransformedNodeNames: { name: string, transformation: number[] }[]) => {
@MajorMeerkatThe3rd detail: we could remove the transformation property from the type definition for `oldTransformedNodeNames`

2024-08-30 05:57 UTC, snabela commented on hooks/shapediver/viewer/interaction/gumball/useGumballEvents.ts
> +					if (node.getPath().endsWith(parts.slice(1).join("."))) {
@MajorMeerkatThe3rd do we not check for the output name (parts[0]) here on purpose?

2024-08-30 06:06 UTC, snabela commented on hooks/shapediver/viewer/interaction/gumball/useGumballEvents.ts
> +			const newTransformedNodeNames = [...transformedNodeNames];
@MajorMeerkatThe3rd the use of `transformedNodeNames` (which is not a dependency, and ideally wouldn't be made a dependency), could lead to trouble, depending on how this hook gets used. Example: If `setTransformedNodeNames` gets called by a caller of the `useGumballEvents` hook, then the gumball event callback will still use the old instance of `transformedNodeNames`. 
Potential solution: Also define a `useRef` below the definition of `transformedNodeNames, set TransformedNodeNames`, and always update its value to `transformedNodeNames`. Use the reference in the event handler callback.

2024-08-30 06:09 UTC, snabela requested changes
Many thanks @MajorMeerkatThe3rd ! I left some comments.

2024-08-30 10:56 UTC, snabela approved these changes
Many thanks @MajorMeerkatThe3rd !

2024-08-30 13:05 UTC, merged